# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions: write-all
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - run: |
        touch .env
        echo "${{secrets.PROD_ENV_FILE}}" > .env

    - name: Install Maven
      run: |
        sudo wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
        sudo sed -i 's/\$releasever/6/g' /etc/yum.repos.d/epel-apache-maven.repo
        sudo yum install -y apache-maven
        mvn --version
    - name: Copy .env to apploication.properties
      run: |
       cat .env >> /home/ec2-user/actions-runner/_work/cloud_labs/cloud_labs/src/main/resources/application.properties
    - name: Stop Spring Boot app
      run: |
        PID=$(ps aux | grep "DB_lab5-0.0.1-SNAPSHOT.jar" | grep -v grep | awk '{print $2}')
        
        if [ -n "$PID" ]; then
          echo "Stopping Spring Boot application with PID $PID"
          kill "$PID"
        else
          echo "Spring Boot application is not running."
        fi
         
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
